load/unload code from https://github.com/cu-ecen-aeld/ldd3/ repo.

diff --git a/base_external/rootfs_overlay/etc/init.d/S98lddmodules b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
--- a/base_external/rootfs_overlay/etc/init.d/S98lddmodules
+++ b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
@@ -2,20 +2,126 @@
 
 KERNEL_VER=`uname -r`
 
-create_scull_devices() {
-    MAJOR=`grep scull /proc/devices | awk '{print $1}'`
-    if [ -z "$MAJOR" ]; then
-	echo "scull module not loaded"
-	exit 1
-    fi
+# Functions below (load/unload) are from https://github.com/cu-ecen-aeld/ldd3/ repo
+load_scull() {
+	module="scull"
+	device="scull"
+	mode="666"
 
-    for i in 0 1 2 3; do
-        rm -f /dev/scull$i
-	mknod /dev/scull$i c $MAJOR $i
-	chmod 666 /dev/scull$i
-    done
+	# Group: since distributions do it differently, look for wheel or use staff
+	if grep -q '^staff:' /etc/group; then
+		group="staff"
+	else
+		group="wheel"
+	fi
 
-    ln -sf /dev/scull0 /dev/scull
+	# invoke insmod with all arguments we got
+	# and use a pathname, as insmod doesn't look in . by default
+	insmod /lib/modules/${KERNEL_VER}/extra/$module.ko $* || exit 1
+
+	# retrieve major number
+	major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
+
+	# Remove stale nodes and replace them, then give gid and perms
+	# Usually the script is shorter, it's scull that has several devices in it.
+
+	rm -f /dev/${device}[0-3]
+	mknod /dev/${device}0 c $major 0
+	mknod /dev/${device}1 c $major 1
+	mknod /dev/${device}2 c $major 2
+	mknod /dev/${device}3 c $major 3
+	ln -sf ${device}0 /dev/${device}
+	chgrp $group /dev/${device}[0-3]
+	chmod $mode  /dev/${device}[0-3]
+
+	rm -f /dev/${device}pipe[0-3]
+	mknod /dev/${device}pipe0 c $major 4
+	mknod /dev/${device}pipe1 c $major 5
+	mknod /dev/${device}pipe2 c $major 6
+	mknod /dev/${device}pipe3 c $major 7
+	ln -sf ${device}pipe0 /dev/${device}pipe
+	chgrp $group /dev/${device}pipe[0-3]
+	chmod $mode  /dev/${device}pipe[0-3]
+
+	rm -f /dev/${device}single
+	mknod /dev/${device}single  c $major 8
+	chgrp $group /dev/${device}single
+	chmod $mode  /dev/${device}single
+
+	rm -f /dev/${device}uid
+	mknod /dev/${device}uid   c $major 9
+	chgrp $group /dev/${device}uid
+	chmod $mode  /dev/${device}uid
+
+	rm -f /dev/${device}wuid
+	mknod /dev/${device}wuid  c $major 10
+	chgrp $group /dev/${device}wuid
+	chmod $mode  /dev/${device}wuid
+
+	rm -f /dev/${device}priv
+	mknod /dev/${device}priv  c $major 11
+	chgrp $group /dev/${device}priv
+	chmod $mode  /dev/${device}priv
+}
+
+unload_scull() {
+	module="scull"
+	device="scull"
+
+	# invoke rmmod with all arguments we got
+	rmmod $module $* || exit 1
+
+	# Remove stale nodes
+	rm -f /dev/${device} /dev/${device}[0-3]
+	rm -f /dev/${device}priv
+	rm -f /dev/${device}pipe /dev/${device}pipe[0-3]
+	rm -f /dev/${device}single
+	rm -f /dev/${device}uid
+	rm -f /dev/${device}wuid
+}
+
+load_faulty() {
+	module="faulty"
+	device="faulty"
+	mode="666"
+
+	set -e
+	# Group: since distributions do it differently, look for wheel or use staff
+	# These are groups which correspond to system administrator accounts
+	if grep -q '^staff:' /etc/group; then
+	    group="staff"
+	else
+	    group="wheel"
+	fi
+
+	echo "Load our module, exit on failure"
+	insmod /lib/modules/${KERNEL_VER}/extra/$module.ko $* || exit 1
+
+	echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
+	major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
+	if [ ! -z ${major} ]; then
+		echo "Remove any existing /dev node for /dev/${device}"
+		rm -f /dev/${device}
+		echo "Add a node for our device at /dev/${device} using mknod"
+		mknod /dev/${device} c $major 0
+		echo "Change group owner to ${group}"
+		chgrp $group /dev/${device}
+		echo "Change access mode to ${mode}"
+		chmod $mode  /dev/${device}
+	else
+		echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
+	fi
+}
+
+unload_faulty() {
+	module="faulty"
+	device="faulty"
+
+	# invoke rmmod with all arguments we got
+	rmmod $module || exit 1
+
+	# Remove stale nodes
+	rm -f /dev/${device}
 }
 
 
@@ -23,18 +129,16 @@ case "$1" in
     start) 
         echo "Starting LDD modules"
 	insmod /lib/modules/${KERNEL_VER}/extra/hello.ko || exit 1
-	insmod /lib/modules/${KERNEL_VER}/extra/scull.ko || exit 1
-	insmod /lib/modules/${KERNEL_VER}/extra/faulty.ko || exit 1
-	# TBD: create device nodes for scull and faulty
+	load_scull
+	load_faulty
         ;;
     stop) 
         echo "Stopping LDD modules"
 	rmmod /lib/modules/${KERNEL_VER}/extra/hello.ko || exit 1
-	rmmod /lib/modules/${KERNEL_VER}/extra/scull.ko || exit 1
-	rmmod /lib/modules/${KERNEL_VER}/extra/faulty.ko || exit 1
-	# TBD: remove device nodes for scull and faulty
+	unload_scull
+	unload_faulty
         ;;
     *)
-        echo "Usage: $0 {start|stop}"
+        echo "Usage: $0 {start|stop} [module_params]"
         exit 1
 esac
